Add new workflow that updates go.sum files
paketo-buildpacks/dep-server pull request #87
Opened 2021-07-19 19:25 UTC by brayanhenao

## Summary
When `dependabot` updates a new dependency it does not modify the `go.sum` files under `actions/get-upstream-dependency/entrypoint` and `actions/list-new-upstream-dependency-versions/entrypoint` that reference the `go.mod` in the root of the project so a problem is generated when one of these actions is used.

I create a new Workflow that updates these files when there is a change in the main `go.mod` file. 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-07-19 20:07 UTC, arjun024 commented
Just wondering why https://github.com/paketo-buildpacks/dep-server/blob/a270512d02e9ba61668c321444d88b4f10bedc31/actions/list-new-upstream-dependency-versions/entrypoint/go.mod#L5-L7 is done instead of `require github.com/paketo-buildpacks/dep-server main`?

Also, wouldn't it fix the go.sum issue if `go mod tidy` is added [here](https://github.com/paketo-buildpacks/dep-server/blob/a270512d02e9ba61668c321444d88b4f10bedc31/actions/list-new-upstream-dependency-versions/action.yml#L35) instead of a workflow that opens PRs?

2021-07-20 13:48 UTC, sophiewigmore commented
@arjun024 I was wondering the same thing. It looks like this `go.mod` file has been like that since it's inception. I believe the version has to be of the form `vx.x.x` and can't be main. If you run a `go get github.com/paketo-buildpacks/dep-server@main`, the `go.mod` gets `v0.0.0-20210716200630-a270512d02e9` added to it instead of `v0.0.0-00010101000000-000000000000 `. I am assuming this is because this repo isn't versioned in any way.

2021-07-20 13:49 UTC, sophiewigmore commented
@arjun024 I hadn't thought about that! I'd love to see a PR for that for this action and `get-upstream-dependency` if you have a chance. That'd definitely work.

2021-07-21 14:45 UTC, sophiewigmore requested changes

2021-07-21 14:45 UTC, sophiewigmore commented on .github/workflows/update-go-sum.yml
> +          go mod tidy
Can you add a case in for `pkg/dependency/test/acceptance` as well please?

2021-07-21 15:48 UTC, sophiewigmore approved these changes

2021-07-21 15:49 UTC, merged